add check for existing files before find word

diff --git a/.local/bin/fd b/.local/bin/fd
--- a/.local/bin/fd
+++ b/.local/bin/fd
@@ -1,10 +1,6 @@
 #!/bin/bash
-set -euo pipefail # エラーや未定義の変数が呼び出された場合プロセスを終了する
+set -euo pipefail
 
-
-###################################
-# 関数定義
-###################################
 # ヘルプを表示する
 function print_usage {
     cat << help_msg
@@ -53,20 +49,22 @@ function find_word {
     local word=${1:-""}
     local dict_file="$HOME/.fd/dict.txt"
 
+    # 辞書ファイルが存在しない場合は --init を促す
+    if [[ ! -f "$dict_file" ]]; then
+        echo "The dictionary file was not found. Please run 'fd --init' to create the dictionary file."
+        exit 1
+    fi
+
     cat "$dict_file" | fzf --exact --tiebreak=begin --prompt="📖 > "  --query="$word"
 }
 
-
-###################################
-# メイン処理
-###################################
 function main() {
     if (( $# == 0 )); then
         find_word
         exit 0
     fi
 
-    # 引数で処理を分岐する
+    # コマンドライン引数で処理を分岐する
     case "$1" in
         -h | --help )
             print_usage
