Revert "create dictionary file automatically when not found"
This reverts commit fdea7a8bd2060b17f380570b178a6b50ca9ef7b9.

diff --git a/.local/bin/fd b/.local/bin/fd
--- a/.local/bin/fd
+++ b/.local/bin/fd
@@ -52,10 +52,10 @@ function create_dict() {
 function find_word() {
     local word=${1:-""}
 
-    # 辞書ファイルが存在しない場合は作成する
+    # 辞書ファイルが存在しない場合は --init を促す
     if [[ ! -f "$DICT_FILE" ]]; then
-        echo "The dictionary file was not found. Creating the dictionary file..."
-        create_dict
+        echo "The dictionary file was not found. Please run 'fd --init' to create the dictionary file."
+        exit 1
     fi
 
     fzf --exact --tiebreak=begin --prompt="📖 > " --query="$word" < "$DICT_FILE"
